name: Build U‑Boot for Quartz64‑A

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "U‑Boot tag (≥ v2023.10); leave blank for 'master'"
        required: false
        default: ""
      defconfig:
        description: "Board defconfig"
        required: false
        default: "quartz64-a-rk3566_defconfig"

jobs:
  build:
    runs-on: ubuntu-latest   # x86_64 runner is fine; we cross‑compile
    env:
      # Location for sources (relative to ${{ github.workspace }})
      UBOOT_DIR: u-boot
      RKBIN_DIR: rkbin
      CROSS_COMPILE: aarch64-linux-gnu-

    steps:
    # 1. Set up the tool‑chain & utilities
    - name: Install build prerequisites
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends \
          build-essential git make gcc-aarch64-linux-gnu binutils-aarch64-linux-gnu \
          device-tree-compiler python3 python3-dev python3-setuptools python3-pyelftools \
          swig libssl-dev libgnutls28-dev pkg-config


    # 2. Fetch sources
    - name: Clone U‑Boot
      run: |
        git clone https://source.denx.de/u-boot/u-boot.git $UBOOT_DIR
        cd $UBOOT_DIR
        if [ -n "${{ github.event.inputs.tag }}" ]; then
          git checkout "${{ github.event.inputs.tag }}"
        fi

    - name: Clone Rockchip firmware binaries
      run: |
        git clone --depth 1 https://github.com/rockchip-linux/rkbin.git $RKBIN_DIR

    # 3. Set ROCKCHIP_TPL and BL31 environment variables
    # ------------------------------------------
    # 1. Locate firmware blobs  ➜  save outputs
    # ------------------------------------------
    - name: Locate Rockchip TPL & BL31
      id: fw
      run: |
        set -euo pipefail
        export ROCKCHIP_TPL=$(realpath $(ls $RKBIN_DIR/bin/rk35/rk3566_ddr_1056MHz_v*.bin | sort | tail -n1))
        export BL31=$(realpath $(ls $RKBIN_DIR/bin/rk35/rk3568_bl31_v*.elf  | sort | tail -n1))
        echo "tpl=$ROCKCHIP_TPL"  >> "$GITHUB_OUTPUT"
        echo "bl31=$BL31" >> "$GITHUB_OUTPUT"
    # ------------------------------------------
    # 3. (Optional but nice) sanity‑check paths
    # ------------------------------------------
    - name: Verify firmware paths
      run: |
        file "$ROCKCHIP_TPL"
        file "$BL31"
    
    # ------------------------------------------
    # 4. Configure & build — no inline vars needed
    # ------------------------------------------
    - name: Configure U‑Boot
      working-directory: ${{ env.UBOOT_DIR }}
      run: make "${{ github.event.inputs.defconfig }}"
    
    - name: Build U‑Boot
      working-directory: ${{ env.UBOOT_DIR }}
      run: make -j"$(nproc)"


    # 5. Build U‑Boot
    - name: Compile U‑Boot
      working-directory: ${{ env.UBOOT_DIR }}
      run: |
        make \
          CROSS_COMPILE=${CROSS_COMPILE} \
          ROCKCHIP_TPL=${ROCKCHIP_TPL} \
          BL31=${BL31} \
          -j"$(nproc)"


    # 6. Expose the artifact
    - name: Upload u‑boot‑rockchip.bin
      uses: actions/upload-artifact@v4
      with:
        name: u-boot-${{ github.event.inputs.defconfig }}
        path: ${{ env.UBOOT_DIR }}/u-boot-rockchip.bin
